Repository angular/material, pull requests merged in 2018-03, with the labels that each got.

#11140 docs(autocomplete): fix typos and inconsistencies
  src/components/autocomplete/js/autocompleteDirective.js
Labels: cla: yes, pr: merge ready, pr: merge safe, type: docs

#11142 docs(virtualRepeat): bullet format issue, typo
  src/components/virtualRepeat/virtual-repeater.js
Labels: cla: yes, pr: merge ready, pr: merge safe, type: docs

#11143 docs(readme): update GitCDN links
  README.md
Labels: P1: urgent, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11149 docs(datepicker): follow Material Design guidelines for messages
  src/components/datepicker/demoValidations/index.html
Labels: P5: nice to have, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: demos

#11148 docs(panel): fix invalid example. improve docs.
  src/components/panel/panel.js
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11152 docs(select): add docs for ng-change
  src/components/checkbox/checkbox.js
  src/components/select/select.js
  src/components/switch/switch.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#11153 docs(sidenav): fix onClose() example
  src/components/sidenav/sidenav.js
Labels: P3: important, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11145 fix(panel): memory leak on destroy
  src/components/panel/panel.js
Labels: P1: urgent, cla: yes, pr: lgtm, pr: merge ready, pr: presubmit-failures, severity: memory leak, severity: regression, type: bug

#11125 feat(md-chips): added validation for ng-required
  src/components/chips/chips.spec.js
  src/components/chips/demoValidation/index.html
  src/components/chips/demoValidation/script.js
  src/components/chips/demoValidation/style.css
  src/components/chips/js/chipsController.js
  src/components/chips/js/chipsDirective.js
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, pr: presubmit-failures, type: enhancement

#11160 docs(dialog): fix typo
  src/components/dialog/dialog.js
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11150 fix(input): make md-maxlength validation happen on initialization
  src/components/input/input.js
  src/components/input/input.spec.js
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, pr: presubmit-failures, reported by Googler

#11163 fix(chips): md-chip-append-delay of 0 does not get converted to 300
  src/components/chips/js/chipsController.js
Labels: P2: required, a11y, cla: yes, pr: merge ready, severity: regression, type: bug

#11109 Fix jshint warnings
  .jshintrc
  src/components/autocomplete/demoInsideDialog/script.js
  src/components/autocomplete/js/autocompleteDirective.js
  src/components/chips/demoContactChips/script.js
  src/components/chips/demoCustomInputs/script.js
  src/components/chips/js/chipDirective.js
  src/components/chips/js/chipsDirective.js
  src/components/colors/demoBasicUsage/script.js
  src/components/colors/demoThemePicker/script.js
  src/components/gridList/grid-list.js
  src/components/icon/demoLoadSvgIconsFromUrl/script.js
  src/components/input/input.js
  src/components/menu/js/menuServiceProvider.js
  src/components/navBar/navBar.js
  src/components/panel/demoGroups/script.js
  src/components/panel/panel.js
  src/components/tabs/js/tabsController.js
  src/components/toast/toast.js
  src/components/truncate/truncate.js
  src/components/virtualRepeat/virtual-repeater.js
  src/core/services/compiler/compiler.js
  src/core/util/util.js
Labels: P5: nice to have, cla: yes, pr: merge ready, type: chore

#11164 docs(dialog): correct and add back resolve property
  src/components/dialog/dialog.js
Labels: P3: important, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11078 fix(dialog) md-colors breaking inside of dialogs
  src/components/dialog/dialog.js
  src/components/dialog/dialog.spec.js
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, severity: regression, type: bug, ui: theme

#10992 feat(navBar): add disabled attribute
  src/components/navBar/demoBasicUsage/index.html
  src/components/navBar/navBar.js
  src/components/navBar/navBar.scss
  src/components/navBar/navBar.spec.js
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready

#9179 feat(bottom-sheet): add isLockedOpen option; general cleanup
  src/components/bottomSheet/bottom-sheet.js
  src/components/bottomSheet/bottom-sheet.spec.js
Labels: P5: nice to have, pr: lgtm, pr: merge ready, type: enhancement

#11186 docs: use AngularJS logo instead of Angular logo
  docs/app/css/style.css
  docs/config/template/index.template.html
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#11169 fix(toast): update style direction to flex-direction
  src/components/toast/toast.scss
Labels: P5: nice to have, cla: yes, pr: lgtm, pr: merge ready, type: bug, ui: CSS

#11166 feat(chips): trigger ng-change on chip addition/removal
  src/components/chips/chips.spec.js
  src/components/chips/demoBasicUsage/index.html
  src/components/chips/demoBasicUsage/script.js
  src/components/chips/demoContactChips/index.html
  src/components/chips/demoContactChips/script.js
  src/components/chips/js/chipsController.js
  src/components/chips/js/chipsDirective.js
  src/components/chips/js/contactChipsDirective.js
Labels: P4: minor, cla: yes, pr: merge ready, type: enhancement

#11185 fix(nav-bar): initial disabled state is now respected
  src/components/button/button.js
  src/components/navBar/navBar.js
  src/components/navBar/navBar.spec.js
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11191 docs(radio-button): update and clean up
  src/components/radioButton/radio-button.js
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11188 docs(getting-started): update links and information
  docs/app/partials/getting-started.tmpl.html
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11180 docs(bottom-sheet): add documentation for `addPreset`
  src/components/bottomSheet/bottom-sheet.js
Labels: P5: nice to have, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#11193 fix(dialog): thread blocks during large DOM traversals
  src/components/dialog/dialog.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, type: performance

#11197 docs(gesture): add missing service and method docs
  src/core/services/gesture/gesture.js
Labels: P2: required, cla: yes, pr: merge ready, type: docs, type: gestures, ui: mobile

#11194 feat(autocomplete): add md-menu-container-class for styling
  src/components/autocomplete/autocomplete.spec.js
  src/components/autocomplete/demoCustomTemplate/index.html
  src/components/autocomplete/demoCustomTemplate/style.global.css
  src/components/autocomplete/js/autocompleteDirective.js
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, type: enhancement
