Repository angular/material, pull requests merged in 2018-11, with the labels that each got.

#11498 docs(pull-requests): add link to Github's Amending guide
  docs/guides/PULL_REQUESTS.md
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11500 fix(autocomplete): updateSize incorrectly sets the size to zero
  src/components/virtualRepeat/virtual-repeater.js
Labels: P4: minor, cla: yes, pr: merge ready, type: bug

#11494 fix(nav-bar): update keyboard navigation to WAI-ARIA guidelines
  package-lock.json
  package.json
  src/components/navBar/navBar.js
  src/components/navBar/navBar.spec.js
Labels: P2: required, a11y, cla: yes, pr: merge ready, type: bug, ui: focus

#11492 fix(theme): prepend # to hex codes enableBrowserColor
  src/core/services/theming/theming.js
  src/core/services/theming/theming.spec.js
Labels: P4: minor, cla: yes, pr: merge ready, type: bug, ui: theme

#11459 fix(switch): theming issues with focus in dark theme
  src/components/switch/switch-theme.scss
  src/components/switch/switch.scss
Labels: P4: minor, cla: yes, pr: merge ready, type: bug, ui: theme

#11491 fix(select): don't change form state when adding to a form
  src/components/select/select.js
  src/components/select/select.spec.js
Labels: P3: important, cla: yes, pr: merge ready, type: bug

#11441 fix(autocomplete): Chromevox indicates selected option on focus
  src/components/autocomplete/js/autocompleteController.js
  src/components/autocomplete/js/autocompleteDirective.js
Labels: P1: urgent, a11y, browser: Chrome, cla: yes, pr: merge ready, reported by Googler, type: bug

#11510 fix(toast): do not auto set any actionKeys
  src/components/toast/demoCustomUsage/script.js
  src/components/toast/toast.js
  src/core/services/aria/aria.js
Labels: P1: urgent, a11y, cla: yes, pr: merge ready, type: bug

#11509 fix(interim): validate the interim element while closing it
  src/core/services/interimElement/interimElement.js
Labels: P1: urgent, cla: yes, pr: lgtm, pr: merge ready, severity: regression, type: bug

#11422 fix(chips): improve screen reader support
  src/components/autocomplete/js/autocompleteController.js
  src/components/autocomplete/js/autocompleteDirective.js
  src/components/chips/demoBasicUsage/index.html
  src/components/chips/demoContactChips/index.html
  src/components/chips/demoContactChips/style.scss
  src/components/chips/demoCustomInputs/index.html
  src/components/chips/demoCustomSeparatorKeys/index.html
  src/components/chips/demoCustomSeparatorKeys/style.scss
  src/components/chips/demoStaticChips/index.html
  src/components/chips/demoValidation/index.html
  src/components/chips/demoValidation/script.js
  src/components/chips/demoValidation/style.scss
  src/components/chips/js/chipsController.js
  src/components/chips/js/chipsDirective.js
  src/components/chips/js/contactChipsController.js
  src/components/chips/js/contactChipsDirective.js
Labels: P2: required, a11y, cla: yes, pr: merge ready, type: bug, type: enhancement

#11432 fix(tabs): min-width not respected on IE11. fix right/left padding
  src/components/tabs/js/tabsController.js
  src/components/tabs/tabs.scss
Labels: Blocked, P2: required, browser: IE, cla: yes, pr: merge ready, pr: presubmit-failures, severity: regression, type: bug

#11513 docs(typography): fix link to Roboto font
  docs/content/CSS/typography.md
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11512 docs(toast): add use of locals to custom toast demo
  package-lock.json
  src/components/toast/demoBasicUsage/index.html
  src/components/toast/demoBasicUsage/script.js
  src/components/toast/demoBasicUsage/style.scss
  src/components/toast/demoCustomUsage/script.js
  src/components/toast/demoCustomUsage/toast-template.html
  src/components/toast/toast.js
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11518 fix(autocomplete): don't resize the container in updateSize()
  src/components/virtualRepeat/virtual-repeater.js
Labels: P1: urgent, cla: yes, severity: regression, type: bug

#11530 build: update to AngularJS 1.7.5
  config/build.config.js
  package-lock.json
  package.json
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: build
