Repository angular/material, pull requests merged in 2018-09, with the labels that each got.

#11429 chore(docs): update from AngularJS 1.6.7 to 1.7.2
  config/build.config.js
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: chore

#11428 feat(theming): add ability to specify hues as options to defineTheme
  src/core/services/theming/theming.js
  src/core/services/theming/theming.spec.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, type: enhancement, ui: theme

#9698 fix(autocomplete): apply theming to input element
  src/components/autocomplete/autocomplete-theme.scss
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, type: bug, ui: theme, ux: integration

#11435 docs(select): add missing docs for md-option and md-optgroup
  src/components/select/select.js
Labels: P3: important, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11424 fix(toast): improve a11y support for $mdToast.simple(). improve docs
  src/components/toast/demoBasicUsage/script.js
  src/components/toast/demoCustomUsage/index.html
  src/components/toast/demoCustomUsage/script.js
  src/components/toast/demoCustomUsage/style.scss
  src/components/toast/demoCustomUsage/toast-template.html
  src/components/toast/toast.js
  src/components/toast/toast.spec.js
Labels: P1: urgent, a11y, cla: yes, pr: lgtm, pr: merge ready, reported by Googler, type: bug

#11442 docs(changelog): add breaking change to md-selected-text for 1.1.2
  CHANGELOG.md
Labels: P1: urgent, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11450 docs(panel): fix ampersands getting parsed into &amp;
  src/components/panel/panel.js
Labels: P5: nice to have, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11439 docs(tabs): clean up the dynamic tabs demo
  src/components/tabs/demoDynamicTabs/index.html
  src/components/tabs/demoDynamicTabs/script.js
  src/components/tabs/demoDynamicTabs/style.scss
  src/components/tabs/js/tabsController.js
Labels: P5: nice to have, cla: yes, pr: merge ready, type: demos

#11440 fix(datepicker): md-open-on-focus constantly re-opens on close w/ IE11
  src/components/datepicker/js/datepickerDirective.js
Labels: P3: important, browser: IE, cla: yes, pr: merge ready, type: bug

#11437 fix(input-container): handle initialization of md-icon with ng-if
  src/components/input/input.js
  src/components/input/input.spec.js
Labels: P4: minor, cla: yes, pr: merge ready, severity: regression, type: bug, ux: polish

#11463 docs: clarify that this project aligns with the MD spec from 2014-2017
  README.md
  docs/app/partials/home.tmpl.html
Labels: P3: important, cla: yes, pr: merge ready, pr: merge safe, type: docs
