Repository angular/material, pull requests merged in 2018-02, with the labels that each got.

#9609 fix(panel): allow numbers in offset methods
  src/components/panel/panel.js
  src/components/panel/panel.spec.js
Labels: P3: important, pr: lgtm, pr: merge ready

#9449 fix(button): fix rendering issue with borders and webkit browsers
  src/components/button/button.scss
Labels: P4: minor, browser: Chrome, browser: Safari, cla: yes, hotlist: animations, pr: lgtm, pr: merge ready, ui: CSS, ui: ink

#10990 fix(dialog): fix prompt closing on ENTER key when input is required and empty
  src/components/dialog/dialog.js
  src/components/dialog/dialog.spec.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, type: bug, ux: integration

#11127 fix(menu): close menu on tab
  src/components/menu/js/menuServiceProvider.js
  src/components/menu/menu.spec.js
Labels: P1: urgent, cla: yes, pr: merge ready, reported by Googler, ui: a11y

#11103 fix(md-menu): allow nested md-menu-content again
  src/components/menu/js/menuDirective.js
  src/components/menu/menu.spec.js
Labels: P1: urgent, cla: yes, pr: lgtm, pr: merge ready, severity: regression, type: bug

#11129 fix(input): prevent md-select-on-focus from refocusing blurred input
  src/components/input/input.js
  src/components/input/input.spec.js
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, ux: integration
