Repository angular/material, pull requests merged in 2018-08, with the labels that each got.

#11396 docs(list): clarify that md-avatar-icon is for use with icons
  src/components/list/list.js
Labels: P5: nice to have, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#11393 fix(list): account for IE11 bug with flexbox and min-height
  src/components/list/list.scss
Labels: P3: important, browser: IE, cla: yes, pr: lgtm, pr: merge ready, type: bug, ui: CSS, ui: layout

#11392 fix(tabs): show a visual indication of tab focus
  src/components/tabs/js/tabsDirective.js
Labels: P1: urgent, a11y, cla: yes, pr: lgtm, pr: merge ready, reported by Googler, severity: regression, type: bug

#11403 fix(autocomplete): announce when an item is selected from the dropdown
  src/components/autocomplete/autocomplete.spec.js
  src/components/autocomplete/demoBasicUsage/index.html
  src/components/autocomplete/js/autocompleteController.js
  src/components/autocomplete/js/autocompleteDirective.js
Labels: P1: urgent, a11y, cla: yes, pr: merge ready, reported by Googler, type: enhancement

#11402 fix(tabs): provide guidance on how to navigate between tabs
  src/components/tabs/js/tabsController.js
  src/components/tabs/js/tabsDirective.js
Labels: P3: important, a11y, cla: yes, pr: merge ready, reported by Googler, type: enhancement, ux: polish

#11404 fix(input): remove placeholder from button accessibility tree
  src/components/input/input.js
Labels: P3: important, a11y, browser: Chrome, cla: yes, pr: merge ready, reported by Googler, type: bug

#11405 feat(autocomplete): add support for aria-describedby
  src/components/autocomplete/demoBasicUsage/index.html
  src/components/autocomplete/demoFloatingLabel/index.html
  src/components/autocomplete/js/autocompleteController.js
  src/components/autocomplete/js/autocompleteDirective.js
Labels: P2: required, a11y, cla: yes, pr: merge ready, reported by Googler, type: enhancement

#11407 feat(autocomplete): add support for aria-labelledby
  src/components/autocomplete/js/autocompleteController.js
  src/components/autocomplete/js/autocompleteDirective.js
Labels: P4: minor, a11y, cla: yes, pr: merge ready, type: enhancement

#11430 build(contributors): don't assume rm command exists on Windows
  gulp/tasks/build-contributors.js
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: build
