Repository angular/material, pull requests merged in 2018-10, with the labels that each got.

#11455 chore(ci): use ChromeHeadless and FirefoxHeadless
  .travis.yml
  README.md
  config/build.config.js
  config/karma-jenkins.conf.js
  config/karma-travis.conf.js
  config/karma.conf.js
  package-lock.json
  package.json
  scripts/test-versions.sh
  scripts/travis-run-script.sh
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: build, type: chore

#11475 docs: address Lighthouse audit issues
  docs/app/css/highlightjs-material.css
  docs/app/css/style.css
  docs/app/partials/getting-started.tmpl.html
  docs/app/partials/home.tmpl.html
  docs/app/partials/layout-introduction.tmpl.html
  docs/config/template/index.template.html
  src/components/autocomplete/demoFloatingLabel/index.html
Labels: P2: required, a11y, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#11453 fix(util,select): extra scrollbar when select dropdown is open
  src/core/util/util.js
Labels: Blocked, P3: important, browser: IE, cla: yes, pr: presubmit-failures, type: bug

#11427 fix(toast): remove the interim element from the list before closing element
  src/core/services/interimElement/interimElement.js
Labels: P2: required, cla: yes, pr: merge ready, reported by Googler, type: bug

#11342 fix(icon): stop breaking id references when caching icon ids
  src/components/icon/demoLoadSvgIconsFromUrl/script.js
  src/components/icon/demoSvgIconSets/script.js
  src/components/icon/demoUsingTemplateRequest/script.js
  src/components/icon/icon.spec.js
  src/components/icon/js/iconDirective.js
  src/components/icon/js/iconService.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, type: bug, type: docs

#11488 fix(nav-bar): set ng-href on nav-item even if md-nav-href is empty
  config/karma-sauce.conf.js
  config/karma-travis.conf.js
  config/karma.conf.js
  package-lock.json
  package.json
  src/components/navBar/navBar.js
  src/components/navBar/navBar.spec.js
Labels: P1: urgent, cla: yes, pr: merge ready, type: bug, type: chore

#11486 fix(nav-bar): improve screen reader support
  src/components/navBar/navBar.js
  src/components/navBar/navBar.spec.js
Labels: P1: urgent, a11y, cla: yes, pr: merge ready, type: bug
