Repository angular/material, pull requests merged in 2018-06, with the labels that each got.

#11317 build(travis): run tests against AngularJS 1.7
  .travis.yml
Labels: P3: important, cla: yes, pr: merge ready, pr: merge safe, type: build

#11310 fix(chips): regression where chips model gets out of sync with view
  src/components/autocomplete/demoBasicUsage/script.js
  src/components/autocomplete/demoCustomTemplate/script.js
  src/components/autocomplete/demoFloatingLabel/script.js
  src/components/autocomplete/demoInsideDialog/script.js
  src/components/chips/chips.spec.js
  src/components/chips/contact-chips.spec.js
  src/components/chips/demoContactChips/index.html
  src/components/chips/demoContactChips/script.js
  src/components/chips/demoCustomInputs/script.js
  src/components/chips/js/chipsController.js
  src/components/chips/js/chipsDirective.js
  src/components/chips/js/contactChipsController.js
  src/components/chips/js/contactChipsDirective.js
Labels: P2: required, cla: yes, hotlist: Angular 1.7 support, pr: merge ready, severity: regression, type: bug

#11331 fix(layout): reduce layout size and fix flex 33/66 outside of layout containers
  docs/app/css/style.css
  docs/app/partials/layout-children.tmpl.html
  src/core/style/layout.scss
Labels: P1: urgent, cla: yes, pr: merge ready, reported by Googler, severity: performance, type: bug, type: docs, ui: layout

#11316 docs(select): clarify behavior of multiple attribute
  src/components/select/select.js
  src/components/select/select.spec.js
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11320 fix(compiler): remove dependency on AngularJS private API
  .travis.yml
  package-lock.json
  package.json
  src/core/services/compiler/compiler.js
  src/core/services/compiler/compiler.spec.js
Labels: P3: important, cla: yes, hotlist: Angular 1.7 support, pr: lgtm, pr: merge ready, type: conflict, type: docs

#11313 fix(select): use KeyboardEvent.key instead of KeyboardEvent.keyCode for auto-completion
  src/components/select/select.js
  src/components/select/select.spec.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11305 fix(chips): unwanted re-focus of last chip after blur
  src/components/chips/demoBasicUsage/index.html
  src/components/chips/demoBasicUsage/readme.html
  src/components/chips/demoBasicUsage/script.js
  src/components/chips/js/chipsController.js
Labels: P1: urgent, a11y, cla: yes, pr: merge ready, severity: regression, type: bug, ui: focus, ux: polish

#11302 fix(ripple): cleanup ripple even when the touch is very quick on iOS
  src/core/services/ripple/ripple.js
Labels: P4: minor, browser: iOS, cla: yes, pr: lgtm, pr: merge ready, type: bug, ui: ink, ui: mobile

#11296 docs(datepicker,dateLocaleProvider): add moment.js demos
  .eslintrc.json
  docs/app/js/codepen.js
  docs/config/template/index.template.html
  package-lock.json
  package.json
  src/components/datepicker/_demoMomentJs/index.html
  src/components/datepicker/_demoMomentJs/script.js
  src/components/datepicker/_demoMomentJs/style.css
  src/components/datepicker/demoMoment/index.html
  src/components/datepicker/demoMoment/script.js
  src/components/datepicker/demoMomentCustomFormat/index.html
  src/components/datepicker/demoMomentCustomFormat/script.js
  src/components/datepicker/js/dateLocaleProvider.js
  src/components/datepicker/js/datepickerDirective.js
Labels: P3: important, cla: yes, pr: merge ready, type: docs

#11267 fix(datepicker): calendar panel supports multi theme scenario
  src/components/datepicker/calendar-theme.scss
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, type: bug, ui: theme

#11098 fix(chips): improve ability to receive focus on click
  src/components/chips/js/chipsController.js
  src/components/chips/js/chipsDirective.js
  src/core/services/interimElement/interimElement.js
Labels: P1: urgent, cla: yes, pr: merge ready, severity: regression, type: bug

#11326 fix(theming): md-theme leaks when child elements are removed
  src/core/services/theming/theming.js
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, reported by Googler, severity: memory leak, type: bug, ui: theme

#11340 fix(css): remove bloat from autoprefixing of unsupported browsers
  README.md
  docs/app/css/style.css
  docs/app/partials/home.tmpl.html
  package-lock.json
  package.json
  scripts/gulp-utils.js
Labels: P3: important, cla: yes, pr: merge ready, severity: performance, type: docs, type: performance, ui: CSS
