Repository angular/material, pull requests merged in 2018-07, with the labels that each got.

#11353 docs(typo): an screenshot-> a screenshot
  README.md
Labels: P5: nice to have, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#11338 fix(input): make md-maxlength validation happen on initialization with interpolated value
  src/components/input/input.js
  src/components/input/input.spec.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready

#11360 build(npm): fix critical npm audit warnings
  gulp/tasks/server.js
  package-lock.json
  package.json
Labels: P1: urgent, cla: yes, pr: merge ready, type: build

#11355 fix(select): display asterisk on label only if empty
  src/components/select/select.scss
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11351 fix(sidenav): refactor syntax to work around issue in babel-minify
  src/components/chips/js/chipsController.js
  src/components/navBar/navBar.js
  src/components/sidenav/sidenav.js
Labels: P4: minor, cla: yes, pr: merge ready, type: conflict

#11365 build(gulp-uglify): use new syntax for preserving some comments
  gulp/util.js
Labels: P1: urgent, cla: yes, pr: merge ready, pr: merge safe, type: build

#8142 feat(contactChips): add basic support for md-separator-keys
  src/components/chips/contact-chips.spec.js
  src/components/chips/demoContactChips/index.html
  src/components/chips/demoContactChips/script.js
  src/components/chips/js/contactChipsController.js
  src/components/chips/js/contactChipsDirective.js
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, type: enhancement

#11364 fix(chips): editing chips works again
  src/components/chips/js/chipController.js
  src/components/chips/js/chipDirective.js
  src/components/chips/js/chipsDirective.js
  src/core/util/util.js
Labels: P2: required, cla: yes, pr: merge ready, severity: regression, type: bug

#11367 docs(codepen): fix missing line break in Copyright
  docs/app/js/codepen.js
Labels: cla: yes, pr: merge ready, pr: merge safe, type: docs

#11368 docs: change to LLC instead of Inc. in Copyright and licenses
  LICENSE
  docs/app/js/codepen.js
  docs/app/partials/license.tmpl.html
Labels: cla: yes, pr: merge ready, pr: merge safe, type: docs

#11369 docs(menu): fix broken link to spec
  src/components/menu/demoMenuPositionModes/script.js
  src/components/menu/demoMenuWidth/index.html
  src/components/menu/demoMenuWidth/script.js
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, severity: regression, type: docs

#11370 docs(card): replace problematic share icon
  docs/app/img/icons/baseline-share-24px.svg
  docs/app/img/icons/share-arrow.svg
  docs/app/svg-assets-cache.js
  src/components/bottomSheet/demoBasicUsage/script.js
  src/components/card/demoBasicUsage/index.html
  src/components/card/demoCardActionButtons/index.html
  src/components/card/demoInCardActions/index.html
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: docs, type: spec alignment

#11371 docs(theming): fix invalid JSDoc syntax
  src/core/services/theming/theming.js
Labels: P5: nice to have, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11380 fix(bottom-sheet): component theme now supports dark mode
  src/components/bottomSheet/bottom-sheet-theme.scss
  src/components/bottomSheet/demoBasicUsage/bottom-sheet-list-template.html
  src/components/bottomSheet/demoBasicUsage/style.css
Labels: P3: important, cla: yes, pr: merge ready, ui: theme

#11381 docs: better support for dark mode in docs and demos
  docs/app/css/style.css
  docs/app/js/app.js
  docs/config/template/index.template.html
  src/components/button/demoBasicUsage/index.html
  src/components/button/demoBasicUsage/script.js
  src/components/button/demoBasicUsage/style.css
  src/components/chips/demoCustomInputs/style.css
  src/components/tabs/demoDynamicHeight/style.scss
  src/components/tabs/demoDynamicTabs/style.scss
  src/components/tabs/demoStaticTabs/index.html
  src/components/tabs/demoStaticTabs/style.scss
  src/components/whiteframe/demoBasicClassUsage/style.css
  src/components/whiteframe/demoDirectiveAttributeUsage/style.css
  src/components/whiteframe/demoDirectiveInterpolation/style.css
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: demos, type: docs, ui: theme

#11352 fix(input): remove unnecessary warnings when ng-messages not provided
  src/components/input/input-animations.spec.js
  src/components/input/input.js
Labels: P1: urgent, cla: yes, hotlist: animations, pr: lgtm, pr: merge ready, type: bug

#11379 perf(tabs): remove unreferenced elements variable from TabsController
  src/components/tabs/js/tabsController.js
Labels: P5: nice to have, cla: yes, pr: merge ready, type: performance

#11374 refactor(virtual-repeat,util): lint and JSDoc cleanup
  src/components/virtualRepeat/virtual-repeater.js
  src/core/util/util.js
Labels: P5: nice to have, cla: yes, pr: merge ready, type: docs

#11373 fix(select): theming issues with md-select-value
  src/components/select/select-theme.scss
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, type: bug, ui: theme

#11372 fix(select): give focus to the first option when loaded asynchronously
  src/components/select/select.js
Labels: P2: required, a11y, cla: yes, pr: lgtm, pr: merge ready, type: bug, ux: polish

#11375 fix(tabs): md-center-tabs causes in high CPU usage
  src/components/tabs/js/tabDirective.js
  src/components/tabs/js/tabsController.js
  src/components/tabs/js/tabsDirective.js
Labels: P1: urgent, cla: yes, pr: merge ready, reported by Googler, severity: performance, type: performance
