Repository angular/material, pull requests merged in 2018-04, with the labels that each got.

#11209 docs(mdThemingProvider): add missing documentation
  src/core/services/theming/theming.js
Labels: P3: important, cla: yes, pr: merge ready, pr: merge safe, type: docs, ui: theme

#11224 docs(getting-started): fix blocked iframes
  docs/app/partials/getting-started.tmpl.html
Labels: cla: yes, pr: merge ready, pr: merge safe, type: docs

#10980 fix(slider): fixed incorrect update of model and min/max values in same digest cycle
  src/components/slider/slider.js
  src/components/slider/slider.spec.js
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11201 fix(datepicker): calendar panel theme supports dark mode
  src/components/datepicker/calendar-theme.scss
  src/components/datepicker/datePicker-theme.scss
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, type: bug, ui: theme

#11210 fix(slider-container): numeric inputs cut off on Firefox and Edge
  src/components/slider/demoBasicUsage/index.html
  src/components/slider/demoBasicUsage/script.js
  src/components/slider/slider.js
Labels: P2: required, browser: FireFox, browser: MS Edge, cla: yes, pr: merge ready, type: bug, type: docs, ui: layout

#11203 fix(autocomplete): autocomplete panel theme supports dark mode
  src/components/autocomplete/autocomplete-theme.scss
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, type: bug, ui: CSS, ui: theme

#11225 feat(md-chips): re-added validation for ng-required
  src/components/chips/chips.spec.js
  src/components/chips/demoValidation/index.html
  src/components/chips/demoValidation/script.js
  src/components/chips/demoValidation/style.css
  src/components/chips/js/chipsController.js
  src/components/chips/js/chipsDirective.js
Labels: P1: urgent, pr: merge ready, reported by Googler, type: bug, type: enhancement

#11234 fix(panel): use $event.target instead of $event.srcElement for Firefox compatibility
  src/components/panel/demoGroups/script.js
  src/components/panel/demoPanelProvider/script.js
  src/components/panel/panel.js
Labels: P3: important, browser: FireFox, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11162 feat(icon): Add support to svg symbol icon set
  docs/app/img/icons/sets/symbol-icons.svg
  src/components/icon/demoSvgIconSets/index.html
  src/components/icon/demoSvgIconSets/script.js
  src/components/icon/icon.spec.js
  src/components/icon/js/iconService.js
Labels: P5: nice to have, cla: yes, pr: lgtm, pr: merge ready, type: enhancement

#11237 feat(chips): trigger ng-change on chip addition/removal
  src/components/chips/chips.spec.js
  src/components/chips/demoBasicUsage/index.html
  src/components/chips/demoBasicUsage/script.js
  src/components/chips/demoContactChips/index.html
  src/components/chips/demoContactChips/script.js
  src/components/chips/js/chipsController.js
  src/components/chips/js/chipsDirective.js
  src/components/chips/js/contactChipsDirective.js
Labels: P1: urgent, pr: lgtm, pr: merge ready, reported by Googler, type: feature

#11248 docs(autocomplete): update and clarify the behavior of the clear button
  src/components/autocomplete/js/autocompleteDirective.js
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11247 fix(layout): some flex directives don't work when on a child of layout="column" or layout="row"
  src/core/services/layout/layout-attributes.scss
  src/core/services/layout/layout.scss
  src/core/style/layout.scss
  src/core/style/structure.scss
  src/core/style/typography.scss
Labels: P2: required, pr: lgtm, pr: merge ready, type: bug, ui: flexbox, ui: layout

#11245 fix(autocomplete): don't show the menu panel when readonly
  src/components/autocomplete/autocomplete.spec.js
  src/components/autocomplete/js/autocompleteController.js
Labels: P3: important, a11y, cla: yes, pr: merge ready, type: bug

#11246 feat(gestures): add ability to disable all gestures for perf
  src/core/services/gesture/gesture.js
Labels: P3: important, cla: yes, pr: merge ready, severity: performance, type: feature, type: gestures, type: performance

#11198 fix(select): options panel theme supports dark mode
  src/components/select/demoSelectedText/index.html
  src/components/select/demoSelectedText/script.js
  src/components/select/select-theme.scss
Labels: P4: minor, cla: yes, pr: merge ready, type: bug, ui: theme

#11230 fix(menu): md-menu panel theme supports dark mode
  src/components/menu/menu-theme.scss
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, type: bug, ui: theme

#11244 fix(autocomplete): align highlight style with spec
  src/components/autocomplete/autocomplete-theme.scss
  src/components/autocomplete/autocomplete.scss
Labels: P4: minor, a11y, cla: yes, pr: lgtm, pr: merge ready, type: bug, type: spec alignment, ui: theme

#11255 docs(mdCompilerProvider): add respectPreAssignBindingsEnabled docs
  src/core/services/compiler/compiler.js
Labels: P3: important, cla: yes, pr: merge safe, reported by Googler, type: docs

#11257 docs(mdCompilerProvider): refinements for clarity
  src/core/services/compiler/compiler.js
Labels: P3: important, cla: yes, pr: merge ready, pr: merge safe, reported by Googler, type: docs

#11260 docs(toolbar,menuBar): add md-toolbar-filler examples
  docs/app/js/app.js
  src/components/menuBar/demoBasicUsage/index.html
  src/components/menuBar/demoDynamicNestedMenus/index.html
  src/components/toolbar/demoBasicUsage/img/icons/favorite.svg
  src/components/toolbar/demoBasicUsage/img/icons/menu.svg
  src/components/toolbar/demoBasicUsage/img/icons/more_vert.svg
  src/components/toolbar/demoBasicUsage/index.html
  src/components/toolbar/demoBasicUsage/script.js
  src/components/toolbar/demoBasicUsage/style.css
  src/components/toolbar/demoBasicUsage/style.scss
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: demos

#11264 build(release): avoid wiping out updates to the changelog
  package-lock.json
  package.json
  release.js
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: build
