Repository angular/material, pull requests merged in 2019-03, with the labels that each got.

#11472 fix:(dialog): prevent multiple dialogs closing on esc
  src/components/dialog/dialog.js
  src/components/dialog/dialog.spec.js
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11638 fix(panel): caching of panels by id is not working
  src/components/panel/panel.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11462 fix(virtual-repeat-container): support horizontal scrollbar in vertical orientation
  src/components/virtualRepeat/virtual-repeater.js
Labels: P4: minor, cla: yes, pr: merge ready, type: bug

#11580 fix(progress-circular): show correct circle arc
  src/components/progressCircular/js/progressCircularDirective.js
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready

#11653 fix(icon): large SVG files can cause icon caching to hang
  src/components/icon/js/iconService.js
Labels: P2: required, cla: yes, pr: merge ready, severity: regression, type: bug

#11667 docs(radiobutton): correct two misspellings on demo
  src/components/radioButton/demoMultiColumn/script.js
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: demos

#11674 fix(input): placeholder hidden when there is also a label on IE11
  src/components/input/input.scss
Labels: P2: required, browser: IE, cla: yes, pr: merge ready, severity: regression

#11570 build: make the build output deterministic and reproducible
  docs/gulpfile.js
  gulp/config.js
  gulp/tasks/build-demo.js
  gulp/tasks/build-js.js
  gulp/tasks/build-module-demo.js
  gulp/tasks/build-scss.js
  gulp/tasks/jshint.js
  gulp/util.js
  scripts/gulp-utils.js
  src/components/icon/icon.scss
  src/core/style/variables.scss
Labels: P3: important, cla: yes, pr: merge ready, type: build

#11641 fix($mdInteraction): clean up events on $rootScope destroy
  src/core/services/interaction/interaction.js
  src/core/services/interaction/interaction.spec.js
Labels: P1: urgent, cla: yes, g3: sync, pr: lgtm, pr: merge ready, severity: memory leak

#11676 refactor(colors): clean up Closure / JSDoc comments and types
  src/components/colors/colors.js
  src/core/util/color.js
Labels: P4: minor, cla: yes, pr: merge ready, type: chore

#11471 fix(interimElement): don't track elements that fail compilation
  src/components/dialog/dialog.spec.js
  src/core/services/interimElement/interimElement.js
Labels: P3: important, cla: yes, g3: sync, pr: lgtm, pr: merge ready, type: bug

#11683 docs(issue-template): make it more clear that this repo is for AngularJS
  .github/ISSUE_TEMPLATE.md
Labels: cla: yes, pr: merge ready, pr: merge safe, type: docs

#11670 fix(autocomplete): default dropdown to position bottom as default
  src/components/autocomplete/autocomplete.spec.js
  src/components/autocomplete/js/autocompleteController.js
  src/core/util/util.js
Labels: P3: important, cla: yes, pr: merge ready, severity: regression, type: bug

#11688 fix(slider): aria attrs are not announced when tabbing in screen readers
  src/components/slider/demoBasicUsage/index.html
  src/components/slider/demoBasicUsage/script.js
  src/components/slider/demoVertical/index.html
  src/components/slider/demoVertical/script.js
  src/components/slider/slider.js
  src/components/slider/slider.spec.js
Labels: P2: required, a11y, cla: yes, g3: sync, pr: merge ready, severity: regression, type: bug

#11686 fix(tabs): use standard wheel event instead of non-standard mousewheel
  src/components/tabs/js/tabScroll.js
  src/components/tabs/js/tabsController.js
  src/core/util/util.js
Labels: P3: important, browser: FireFox, cla: yes, pr: merge ready, type: bug

#11671 docs(scroll): scroll to top on route change
  docs/app/js/app.js
  docs/config/template/index.template.html
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#11694 docs(changelog): minor fixes
  CHANGELOG.md
Labels: cla: yes, pr: merge ready, pr: merge safe, type: docs
