Repository angular/material, pull requests merged in 2019-02, with the labels that each got.

#11600 fix(nav-bar): improve focus behavior for click events
  src/components/navBar/navBar.js
  src/components/navBar/navBar.scss
  src/components/navBar/navBar.spec.js
Labels: P1: urgent, cla: yes, pr: merge ready, severity: regression, type: bug

#11626 Revert "fix(autocomplete): show dropdown on top only when there is room"
  src/components/autocomplete/js/autocompleteController.js
Labels: cla: yes

#11630 style(lint): fix missing space in checkbox.js
  src/components/checkbox/checkbox.js
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: chore

#11633 fix(tabs): tabbing into tabs component requires an extra tab key press
  src/components/tabs/js/tabsController.js
Labels: P1: urgent, cla: yes, pr: merge ready, severity: regression, type: bug

#11590 docs(util): fix incorrect Closure types and JSDoc
  src/core/util/util.js
Labels: P5: nice to have, cla: yes, pr: merge ready, type: docs

#11629 fix(autocomplete): show dropdown on top only when there is room
  src/components/autocomplete/js/autocompleteController.js
Labels: P3: important, cla: yes, pr: merge ready, type: bug

#11606 docs(ripple): break out docs for $mdInkRippleProvider from $mdInkRipple
  src/core/services/ripple/ripple.js
Labels: P3: important, cla: yes, pr: merge ready, type: docs

#11634 docs: links from header directives are not compatible with base URL
  docs/app/css/style.css
  docs/app/js/anchor.js
  docs/app/js/app.js
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11636 docs(menu): fix docs nav menu margin
  docs/app/css/style.css
  src/components/input/input.js
Labels: P1: urgent, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11635 fix(icon): SVG elements are not loaded from the cache properly on IE11
  src/components/icon/js/iconService.js
  src/core/util/util.js
Labels: P1: urgent, browser: IE, cla: yes, pr: merge ready, severity: regression, type: bug

#11640 fix(checkbox): enter submits form when submit button is disabled
  src/components/checkbox/checkbox.js
  src/components/checkbox/checkbox.spec.js
  src/core/util/util.js
Labels: P1: urgent, a11y, cla: yes, g3: reported, pr: lgtm, pr: merge ready, severity: regression, type: bug

#11645 chore: change npm login check to correct account
  release.js
Labels: cla: yes, pr: merge safe

#11646 docs(changelog): update date of 1.1.13 release
  CHANGELOG.md
Labels: cla: yes, pr: merge ready, pr: merge safe, type: docs

#11648 docs: properly format anchor names and hrefs
  docs/app/js/anchor.js
  docs/app/js/app.js
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: docs
