Repository angular/material, pull requests merged in 2019-07, with the labels that each got.

#11757 fix(autocomplete): options panel flickers on hover after clicking input
  src/components/autocomplete/js/autocompleteController.js
  src/components/autocomplete/js/autocompleteDirective.js
  src/core/util/util.js
Labels: P1: urgent, cla: yes, g3: reported, g3: sync, pr: merge ready, severity: regression, type: bug

#11758 fix(autocomplete): support ng-click on md-autocomplete
  src/components/autocomplete/autocomplete.spec.js
  src/components/autocomplete/js/autocompleteDirective.js
Labels: P1: urgent, cla: yes, g3: reported, g3: sync, pr: merge ready, severity: regression, type: bug

#11749 fix(tooltip, compiler): document.contains is not defined in IE11
  src/core/services/compiler/compiler.js
  src/core/services/gesture/gesture.js
  src/core/util/util.js
Labels: P2: required, browser: IE, cla: yes, pr: merge ready, severity: regression, type: bug

#11755 fix(gesture): check if navigator is defined before accessing userAgent
  src/core/services/gesture/gesture.js
Labels: P2: required, cla: yes, pr: merge ready, severity: regression, type: bug

#11579 fix(rtl): support applying dir="rtl" on DOM elements other than the body
  src/components/gridList/grid-list.js
  src/components/menu/js/menuServiceProvider.js
  src/components/panel/panel.js
  src/components/slider/slider.js
  src/components/tabs/js/tabsController.js
  src/components/virtualRepeat/virtual-repeater.js
  src/core/util/util.js
Labels: P3: important, cla: yes, i18n: bi-directional, pr: lgtm, pr: merge ready, type: enhancement
