Repository angular/material, pull requests merged in 2019-06, with the labels that each got.

#11737 build(release): detect that gulp is not installed globally
  release.js
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#11740 fix(datepicker): remove invalid aria-expanded
  src/components/datepicker/js/datepickerDirective.js
  src/components/datepicker/js/datepickerDirective.spec.js
Labels: P4: minor, a11y, cla: yes, pr: merge ready, type: bug

#11681 fix(panel): append panel animation transforms after existing transforms
  src/components/panel/panel.js
  src/components/panel/panel.spec.js
Labels: P4: minor, cla: yes, hotlist: animations, pr: lgtm, pr: merge ready

#11625 fix(autocomplete): tap outside options panel on iOS does not close panel
  src/components/autocomplete/js/autocompleteController.js
  src/components/bottomSheet/bottom-sheet.js
  src/core/util/util.js
Labels: P2: required, cla: yes, g3: sync, os: iOS, pr: merge ready, type: gestures, ui: mobile

#11754 build: set engines to disable NodeJS 12 due to Gulp 3
  package.json
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: build
