Repository angular/material, pull requests merged in 2019-01, with the labels that each got.

#11567 fix(tabs): md-center-tabs causes tabs to not render
  docs/app/partials/layout-children.tmpl.html
  src/components/tabs/demoCenterTabs/index.html
  src/components/tabs/demoCenterTabs/script.js
  src/components/tabs/demoCenterTabs/style.scss
  src/components/tabs/demoDynamicHeight/index.html
  src/components/tabs/demoDynamicTabs/index.html
  src/components/tabs/demoDynamicTabs/script.js
  src/components/tabs/js/tabsController.js
  src/components/tabs/js/tabsDirective.js
  src/components/tabs/tabs.scss
Labels: P1: urgent, cla: yes, pr: merge ready, severity: regression, type: bug

#11572 fix(select): evaluate md-input-has-value on next tick
  src/components/select/select.js
  src/components/select/select.spec.js
Labels: P1: urgent, cla: yes, pr: lgtm, pr: merge ready, severity: regression, type: bug

#11110 fix(datepicker): validation error when adding text after date
  src/components/datepicker/js/datepickerDirective.js
  src/components/datepicker/js/datepickerDirective.spec.js
Labels: Blocked, P1: urgent, browser: IE, cla: yes, pr: merge ready, pr: presubmit-failures, severity: regression, type: bug

#11576 docs(changelog): add contributors section for 1.1.12
  CHANGELOG.md
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11575 fix(autocomplete): show dropdown on top only when there is room
  src/components/autocomplete/js/autocompleteController.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, type: bug, ux: integration

#11564 fix(radio-group): style focused but unchecked radio buttons
  src/components/radioButton/radio-button-theme.scss
  src/components/radioButton/radio-button.scss
Labels: P2: required, a11y, cla: yes, pr: merge ready, type: bug

#11529 fix(autocomplete): suggestions can be highlighted incorrectly
  src/components/autocomplete/autocomplete-theme.scss
  src/components/autocomplete/js/autocompleteDirective.js
Labels: P3: important, a11y, cla: yes, pr: merge ready, type: bug

#11544 fix(select): carrot not aligned to end in IE11
  src/components/select/select.scss
Labels: P2: required, browser: IE, cla: yes, pr: merge ready, type: bug, ui: CSS

#11539 fix(list): case where user is unable to interact w/ secondary actions
  src/components/list/list.scss
Labels: P4: minor, cla: yes, pr: merge ready, type: bug, ui: CSS, ux: integration

#11528 fix(autocomplete): two chips added on enter w/ IE11
  src/components/autocomplete/autocomplete.spec.js
  src/components/autocomplete/js/autocompleteController.js
Labels: P3: important, a11y, browser: IE, cla: yes, pr: merge ready

#11526 feat(datepicker,calendar): md-date-filter disables months in month mode
  src/components/datepicker/demoValidations/index.html
  src/components/datepicker/demoValidations/script.js
  src/components/datepicker/js/calendar.js
  src/components/datepicker/js/calendarYearBody.js
Labels: P3: important, cla: yes, pr: merge ready, type: enhancement

#11521 fix(datepicker): does not open on focus in Firefox
  src/components/datepicker/js/datepickerDirective.js
Labels: P2: required, browser: FireFox, cla: yes, pr: merge ready, type: bug

#11520 fix(tabs): exception when no selection and header clicked
  src/components/tabs/js/tabsController.js
Labels: P4: minor, cla: yes, pr: merge ready, type: bug

#11588 style(eslint): enable no-trailing-spaces rule
  .eslintrc.json
  docs/app/js/codepen.js
  docs/config/processors/componentsData.js
  scripts/find-max-version.js
  src/components/autocomplete/autocomplete.spec.js
  src/components/chips/chips.spec.js
  src/components/chips/js/chipRemoveDirective.js
  src/components/content/content.spec.js
  src/components/input/input-animations.spec.js
  src/components/sidenav/sidenav.js
  src/components/sidenav/sidenav.spec.js
  src/components/slider/slider.js
  src/components/slider/slider.spec.js
  src/components/sticky/sticky.js
  src/components/tabs/js/tabsDummyWrapperDirective.js
  src/components/virtualRepeat/demoDeferredLoading/script.js
  src/components/whiteframe/demoDirectiveInterpolation/script.js
  src/core/services/interimElement/interimElement.spec.js
  src/core/util/media.spec.js
  src/core/util/prefixer.spec.js
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: chore

#10926 chore: add a Git .mailmap with my new name
  .mailmap
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: chore

#11585 style(eslint): enable spaced-comment rule
  .eslintrc.json
  config/karma-sauce.conf.js
  config/karma.conf.js
  config/ngModuleData.js
  docs/app/js/app.js
  docs/app/js/demoInclude.js
  docs/app/js/highlight-angular.js
  docs/config/processors/componentsData.js
  gulp/tasks/ddescribe-iit.js
  gulpfile.js
  release.js
  src/components/autocomplete/js/autocompleteController.js
  src/components/button/button.js
  src/components/datepicker/js/calendarMonth.js
  src/components/dialog/dialog.js
  src/components/dialog/dialog.spec.js
  src/components/fabSpeedDial/fabController.js
  src/components/menu/js/menuServiceProvider.js
  src/components/progressLinear/progress-linear.js
  src/components/select/select.js
  src/components/select/select.spec.js
  src/components/sticky/sticky.js
  src/components/switch/switch.js
  src/components/tabs/js/tabsController.js
  src/components/tabs/tabs.spec.js
  src/components/toast/toast.js
  src/components/toolbar/toolbar.spec.js
  src/core/services/gesture/gesture.js
  src/core/services/gesture/gesture.spec.js
  src/core/services/theming/theming.js
  src/core/util/animation/animateCss.js
  src/core/util/util.js
  src/core/util/util.spec.js
  updateVersionPicker.js
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: chore

#11595 chore(git): update .mailmap file
  .mailmap
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: chore

#11587 style(eslint): enable array-bracket-spacing rule
  .eslintrc.json
  config/ngModuleData.js
  docs/app/js/app.js
  docs/config/processors/buildConfig.js
  gulp/tasks/build-all-modules.js
  gulp/tasks/ddescribe-iit.js
  release.js
  src/components/button/button.js
  src/components/gridList/demoDynamicTiles/script.js
  src/components/menu/menu.spec.js
  src/components/progressLinear/demoBasicUsage/script.js
  src/components/progressLinear/progress-linear.js
  src/components/select/select.spec.js
  src/components/toast/toast.js
  src/core/services/gesture/gesture.js
  src/core/services/interimElement/interimElement.spec.js
  src/core/services/layout/layout.js
  src/core/services/registry/componentRegistry.js
  src/core/util/iterator.js
  src/core/util/iterator.spec.js
  src/core/util/util.js
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: chore

#11586 style(eslint): enable keyword-spacing rule
  .eslintrc.json
  docs/app/js/app.js
  docs/app/js/codepen.js
  docs/app/js/demo.js
  scripts/gulp-utils.js
  src/components/datepicker/js/datepickerDirective.js
  src/components/gridList/demoDynamicTiles/script.js
  src/components/gridList/grid-list.js
  src/components/icon/icon.spec.js
  src/components/input/input.js
  src/components/menu/js/menuServiceProvider.js
  src/components/panel/demoPanelAnimations/script.js
  src/components/panel/panel.js
  src/components/progressCircular/js/progressCircularDirective.js
  src/components/progressLinear/progress-linear.js
  src/components/radioButton/radio-button.js
  src/components/select/select.js
  src/components/tabs/js/tabsDummyWrapperDirective.js
  src/components/virtualRepeat/demoScrollTo/script.js
  src/components/virtualRepeat/virtual-repeater.js
  src/core/services/aria/aria.js
  src/core/services/gesture/gesture.js
  src/core/services/layout/layout.js
  src/core/services/registry/componentRegistry.js
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: chore

#11516 autocomplete: support variable height autocomplete list items
  src/components/autocomplete/autocomplete-theme.scss
  src/components/autocomplete/autocomplete.scss
  src/components/autocomplete/autocomplete.spec.js
  src/components/autocomplete/demoRepeatMode/img/icons/octicon-repo.svg
  src/components/autocomplete/demoRepeatMode/index.html
  src/components/autocomplete/demoRepeatMode/script.js
  src/components/autocomplete/demoRepeatMode/style.global.css
  src/components/autocomplete/js/autocompleteController.js
  src/components/autocomplete/js/autocompleteDirective.js
Labels: P3: important, cla: yes, pr: from Googler, pr: merge ready, type: enhancement

#11608 chore(ci): enable CircleCI snapshot and doc publishing
  .circleci/config.yml
  config/build.config.js
  package.json
  scripts/bower-material-release.sh
  scripts/snapshot-docs-site.sh
Labels: P3: important, cla: yes, pr: merge ready, pr: merge safe, type: build, type: chore

#11614 chore(ci): fix CircleCI snapshot and doc publishing
  .circleci/config.yml
  scripts/circleci/update-snapshot-and-docs.sh
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: build, type: chore

#11616 chore(ci): adjust working directory before running scripts
  scripts/circleci/update-snapshot-and-docs.sh
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: build, type: chore

#11618 chore(ci): sudo install gulp globally
  .circleci/config.yml
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: build, type: chore

#11619 chore(ci): disable CircleCI's forcing of SSH with GitHub
  scripts/bower-material-release.sh
  scripts/snapshot-docs-site.sh
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: build, type: chore

#11622 chore(ci): use portable sed commands
  scripts/snapshot-docs-site.sh
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: build, type: chore

#11623 chore(ci): update git credential syntax
  scripts/bower-material-release.sh
  scripts/snapshot-docs-site.sh
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: build, type: chore

#11624 chore(ci): only unset the CircleCI SSH override once
  .circleci/config.yml
  scripts/bower-material-release.sh
  scripts/snapshot-docs-site.sh
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: build, type: chore
