Repository angular/material, pull requests merged in 2019-04, with the labels that each got.

#11697 docs: switch from cdn.gitcdn.link to gitcdn.xyz. update dependencies
  README.md
  config/build.config.js
  docs/config/template/index.template.html
  package-lock.json
  package.json
  release.js
  scripts/snapshot-docs-site.sh
  src/components/autocomplete/js/autocompleteDirective.js
Labels: P1: urgent, cla: yes, pr: merge ready, pr: merge safe, type: demos, type: docs

#11695 chore(release): workaround npm issue where .git/ dir is published
  release.js
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, severity: regression, type: bug, type: chore

#11465 fix(icon): stop breaking SVGs that have id references
  src/components/icon/icon.spec.js
  src/components/icon/js/iconService.js
Labels: P2: required, a11y, cla: yes, g3: sync, pr: merge ready, type: bug

#11690 docs(migration): add reference document for migration
  docs/app/js/app.js
  docs/app/js/highlight.pack.js
  docs/content/Theming/01_introduction.md
  docs/content/migration.md
  src/components/colors/colors.js
  src/components/swipe/swipe.js
  src/core/services/ripple/ripple.js
  src/core/services/theming/theming.js
Labels: P1: urgent, cla: yes, hotlist: ngUpgrade, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#11712 docs: allow up/down/page up/page down to scroll docs content
  docs/app/css/style.css
  docs/app/js/anchor.js
  docs/app/js/app.js
  docs/config/template/index.template.html
Labels: P1: urgent, a11y, cla: yes, pr: merge ready, pr: merge safe, severity: critical, type: docs

#11711 fix(tabs): new tab animation broken by code to support IE11
  package-lock.json
  package.json
  src/components/tabs/demoDynamicTabs/script.js
  src/components/tabs/js/tabDirective.js
  src/components/tabs/js/tabsController.js
  src/core/util/util.js
Labels: P1: urgent, cla: yes, g3: sync, pr: merge ready, severity: regression, type: bug

#11658 chore(tests): use beforeAll where possible
  test/angular-material-spec.js
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: chore

#11659 chore(tests): remove unused phantomJS workaround
  test/angular-material-spec.js
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: chore
