Repository angular/material, pull requests merged in 2020-05, with the labels that each got.

#11901 build(select): handle sharing input variables between input and select
  gulp/config.js
  gulp/util.js
  src/components/bottomSheet/bottom-sheet.scss
  src/components/checkbox/checkbox.scss
  src/components/input/_input-variables.scss
  src/components/input/input.scss
  src/core/style/_mixins.scss
  src/core/style/_variables.scss
  src/core/util/constant.js
Labels: P1: urgent, cla: yes, pr: lgtm, pr: merge ready, type: build

#10079 feat(input): add animation to color change
  CHANGELOG.md
  src/components/input/input.scss
Labels: P3: important, cla: no, hotlist: animations, pr: merge ready, type: spec alignment, ux: polish

#11899 build: update to jquery 3.5.1
  .circleci/config.yml
  package-lock.json
  package.json
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: build

#11902 docs: fix contact chips CodePens and update Copyright years
  LICENSE
  docs/app/js/codepen.js
  docs/app/partials/license.tmpl.html
  src/components/chips/demoContactChips/script.js
Labels: P3: important, cla: yes, pr: merge ready, pr: merge safe, type: demos, type: docs

#11903 build(ci): update to latest circleci/node image
  .circleci/config.yml
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: build

#11896 fix(progress-circular): correct rendering for diameter bigger than 60
  src/components/progressCircular/js/progressCircularDirective.js
Labels: P3: important, browser: Chrome, browser: IE, cla: yes, hotlist: animations, pr: merge ready, type: bug

#11905 docs: add SECURITY.md
  SECURITY.md
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#9631 fix(panel): consolidate redundant validations
  src/components/panel/panel.js
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11911 fix(util): sanitize function used by select and autocomplete throws
  src/core/util/util.js
  src/core/util/util.spec.js
Labels: P1: urgent, cla: yes, pr: lgtm, pr: merge ready, severity: regression, type: bug

#11771 fix(select): optgroups are not visible to screen readers
  src/components/select/demoOptionGroups/index.html
  src/components/select/demoOptionGroups/script.js
  src/components/select/select.js
  src/components/select/select.spec.js
Labels: P2: required, a11y, cla: yes, g3: reported, g3: sync, pr: lgtm, pr: merge ready, type: bug

#11906 feat(calendar): support specifying timezone in ng-model-options
  package-lock.json
  src/components/datepicker/js/calendar.js
  src/components/datepicker/js/calendarMonth.js
  src/components/datepicker/js/calendarMonthBody.js
  src/components/datepicker/js/calendarYear.js
  src/components/datepicker/js/calendarYearBody.js
  src/components/datepicker/js/dateLocaleProvider.js
  src/components/datepicker/js/dateUtil.js
  src/components/datepicker/js/datepickerDirective.js
  src/core/util/util.js
Labels: P2: required, cla: yes, i18n: localization, pr: lgtm, pr: merge ready, type: enhancement, ux: integration

#11915 chore: add .nvmrc file
  .gitignore
  .nvmrc
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: chore

#11916 fix(select): revert removal of support for ng-selected on md-options
  src/components/select/select.js
  src/components/select/select.spec.js
Labels: P2: required, cla: yes, pr: merge ready, severity: regression, type: bug

#11917 fix(toast): onRemove doesn't return a Promise in some cases
  package-lock.json
  package.json
  src/components/toast/toast.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11918 fix(calendar, datepicker): in year view, md-date-filter only evaluates first day of month
  src/components/datepicker/demoValidations/index.html
  src/components/datepicker/demoValidations/script.js
  src/components/datepicker/js/calendar.js
  src/components/datepicker/js/calendarYearBody.js
  src/components/datepicker/js/datepickerDirective.js
  src/components/datepicker/js/datepickerDirective.spec.js
Labels: P1: urgent, cla: yes, g3: reported, g3: sync, pr: merge ready, severity: regression, type: bug, type: enhancement

#11920 fix(datepicker): update error state only after $validate has run
  src/components/datepicker/js/datepickerDirective.js
  src/components/datepicker/js/datepickerDirective.spec.js
Labels: P2: required, cla: yes, pr: merge ready, type: bug
