Repository angular/material, pull requests merged in 2020-08, with the labels that each got.

#11993 docs(changelog): update 1.2.0 changelog
  CHANGELOG.md
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#11994 fix(select): respect theme color when select has a value and focus
  src/components/select/select.scss
Labels: P1: urgent, cla: yes, pr: lgtm, pr: merge ready, type: bug, ui: theme

#12002 fix(datepicker): min-date validation is incorrect in GMT+X timezones
  package-lock.json
  package.json
  src/components/datepicker/js/dateUtil.js
  src/components/datepicker/js/datepickerDirective.js
Labels: P1: urgent, cla: yes, i18n: localization, pr: merge ready, severity: regression, type: bug

#12001 fix(datepicker): min-date validation is incorrect in GMT+X timezones
  package.json
  src/components/datepicker/js/dateUtil.js
  src/components/datepicker/js/datepickerDirective.js
Labels: P1: urgent, cla: yes, i18n: localization, pr: lgtm, pr: merge ready, severity: regression, type: bug

#12004 fix(calendar, datepicker): fix issues with GMT+X timezones
  src/components/datepicker/js/calendar.js
  src/components/datepicker/js/dateUtil.js
  src/components/datepicker/js/datepickerDirective.js
Labels: P2: required, cla: yes, i18n: localization, pr: lgtm, pr: merge ready, type: bug

#12003 fix(calendar, datepicker): fix issues with GMT+X timezones
  src/components/datepicker/js/calendar.js
  src/components/datepicker/js/dateUtil.js
  src/components/datepicker/js/datepickerDirective.js
Labels: P2: required, cla: yes, i18n: localization, pr: lgtm, pr: merge ready, type: bug
