Repository angular/material, pull requests merged in 2020-04, with the labels that each got.

#11887 build(docs): speed up rebuilds in development mode
  gulp/tasks/docs.js
Labels: P3: important, cla: yes, pr: merge ready, pr: merge safe, type: build

#11889 docs(dialog): clarify promise rejection behavior in descriptions
  src/components/dialog/dialog.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#11888 docs: fix View Demo button for directives w/o a demo. update icons, Bower references
  README.md
  docs/app/css/style.css
  docs/app/img/icons/github.svg
  docs/app/img/icons/npm-logo.svg
  docs/app/partials/getting-started.tmpl.html
  docs/app/svg-assets-cache.js
  docs/config/template/index.template.html
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#11891 fix(select): menuController not defined edge case in focusOptionNode
  src/components/select/demoBasicUsage/script.js
  src/components/select/select.js
Labels: P1: urgent, cla: yes, pr: merge ready, severity: regression

#11890 docs: updates to landing page and getting started
  .github/ISSUE_TEMPLATE.md
  docs/app/css/style.css
  docs/app/partials/getting-started.tmpl.html
  docs/app/partials/home.tmpl.html
  docs/app/partials/layout-tips.tmpl.html
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: docs

#11892 build: support NodeJS v12 and v14. release script updates.
  package-lock.json
  package.json
  release.js
  scripts/bower-material-release.sh
  scripts/release.sh
  scripts/snapshot-docs-site.sh
  scripts/utils.inc
Labels: P1: urgent, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: build

#11900 docs(changelog): update 1.1.22 changelog
  CHANGELOG.md
  package-lock.json
  package.json
Labels: P1: urgent, cla: yes, pr: merge ready, pr: merge safe, type: docs

#9940 feat(select): add the ability to pre-select the only option in the list
  src/components/select/select.js
  src/components/select/select.spec.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, type: enhancement

#11894 fix(select): perform correct position calculation in rtl for long labels
  src/components/select/select.js
Labels: P3: important, cla: yes, i18n: bi-directional, pr: merge ready, type: bug

#11886 fix(select): height changes when disabled
  src/components/select/select.scss
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11856 fix(panel): can't be reopened after being hidden
  src/components/panel/demoReuse/index.html
  src/components/panel/demoReuse/panel.tmpl.html
  src/components/panel/demoReuse/script.js
  src/components/panel/demoReuse/style.global.css
  src/components/panel/panel.js
Labels: P2: required, cla: yes, hotlist: animations, pr: lgtm, pr: merge ready, type: bug

#11858 fix(compiler): $onDestroy hook not called
  src/core/services/compiler/compiler.js
  src/core/services/compiler/compiler.spec.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, type: enhancement

#11895 fix(progress-linear,progress-circular): mirror indicator when rtl is on
  src/components/progressCircular/progress-circular.scss
  src/components/progressLinear/progress-linear.scss
Labels: P4: minor, cla: yes, i18n: bi-directional, pr: lgtm, pr: merge ready, type: bug
