Repository angular/material, pull requests merged in 2020-11, with the labels that each got.

#12042 docs(contributing): update content and refine grammar
  .github/CONTRIBUTING.md
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#12031 docs: add details about long term support
  README.md
  SECURITY.md
  docs/app/partials/home.tmpl.html
Labels: P1: urgent, cla: yes, pr: lgtm, pr: merge safe, type: docs

#12045 fix(radio): radio buttons cause errors in IE11
  src/core/services/aria/aria.js
Labels: P1: urgent, browser: IE, cla: yes, needs: squash commits, pr: lgtm, pr: merge ready, severity: regression, type: bug

#12047 fix(checkbox): aria-checked state is not computed correctly in all cases
  src/components/checkbox/checkbox.js
  src/components/checkbox/checkbox.spec.js
Labels: P2: required, a11y, cla: yes, pr: lgtm, pr: merge ready, type: bug
