Repository angular/material, pull requests merged in 2020-06, with the labels that each got.

#11924 docs(tabs): improve correctness of API docs and types
  src/components/tabs/js/tabsController.js
  src/components/tabs/js/tabsDirective.js
Labels: P3: important, cla: yes, pr: merge ready, type: docs

#11925 test: enable headless browsers by default
  config/karma.conf.js
Labels: P4: minor, cla: yes, pr: merge ready, pr: merge safe, type: chore

#11929 fix(list): allow overriding list-item padding for clickable items
  src/components/list/list.scss
Labels: P3: important, cla: yes, pr: merge ready, type: bug, ui: CSS

#11936 fix(toolbar): md-scroll-shrink conflicts with md-select in toolbar
  src/components/toolbar/toolbar.js
  src/core/util/util.js
  src/core/util/util.spec.js
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, type: bug, ux: integration

#11937 fix(select): md-focused not removed from options on panel close
  src/components/select/select.js
  src/components/select/select.spec.js
  src/core/services/interimElement/interimElement.js
Labels: P2: required, a11y, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11934 fix(menu-bar): close just nested menu when escape key is pressed
  src/components/menu/js/menuServiceProvider.js
  src/components/menuBar/menu-bar.spec.js
Labels: P2: required, a11y, cla: yes, g3: sync, pr: lgtm, pr: merge ready, type: bug

#11939 fix(calendar): revert removal of workaround for virtual repeat issue
  src/components/datepicker/js/calendar.js
  src/components/datepicker/js/calendarMonthBody.js
  src/components/datepicker/js/calendarYearBody.js
Labels: P1: urgent, cla: yes, pr: lgtm, pr: merge ready, severity: regression, type: bug

#11801 fix(slider): vertical slider in a scrolled container sets value to zero on all clicks
  src/components/slider/slider.js
  src/components/slider/slider.spec.js
Labels: P2: required, cla: yes, pr: merge ready, type: bug

#11938 docs(interimElement): improve documentation
  src/core/services/interimElement/interimElement.js
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, type: docs

#11940 fix(layout): Syntax Error: Token '&&' not a primary expression
  src/core/services/layout/layout.js
  src/core/services/layout/layout.spec.js
Labels: P3: important, cla: yes, g3: sync, hotlist: Angular 1.6 support, pr: merge ready, severity: regression, type: bug

#11942 fix(panel): use existing _md-panel-offscreen class instead of inline styles
  docs/content/Theming/01_introduction.md
  docs/content/performance/internet-explorer.md
  src/components/datepicker/js/dateLocaleProvider.js
  src/components/datepicker/js/datepickerDirective.js
  src/components/panel/panel.js
  src/components/panel/panel.spec.js
  src/core/services/compiler/compiler.js
  src/core/services/theming/theming.js
Labels: P1: urgent, cla: yes, pr: merge ready, severity: regression, type: bug

#11951 fix(datepicker): support ng-model-options timezone w/ Moment
  package.json
  src/components/datepicker/demoNgModelOptionsTimezone/index.html
  src/components/datepicker/demoNgModelOptionsTimezone/script.js
  src/components/datepicker/js/calendar.js
  src/components/datepicker/js/calendarMonth.js
  src/components/datepicker/js/calendarYear.js
  src/components/datepicker/js/dateUtil.js
  src/components/datepicker/js/datepickerDirective.js
  src/core/util/util.js
Labels: P1: urgent, cla: yes, i18n: localization, pr: merge ready, type: bug

#11904 fix(toast): improve position handling to better align with docs
  src/components/toast/toast.js
  src/core/util/util.js
Labels: - Breaking Change, P3: important, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11944 fix(checkbox) update CSS to match spec
  src/components/checkbox/checkbox.scss
  src/components/checkbox/demoBasicUsage/index.html
  src/core/style/_variables.scss
Labels: - Breaking Change, CSS: High Density, P2: required, a11y, cla: no, g3: reported, pr: merge ready, type: spec alignment, ui: CSS

#11921 fix(input-container): align indentation with spec
  src/components/input/_input-variables.scss
  src/components/input/input.scss
  src/components/select/select.scss
Labels: - Breaking Change, P3: important, cla: yes, pr: lgtm, pr: merge ready, type: spec alignment, ui: CSS

#11154 fix(checkbox): handle links in transcluded label in an a11y-friendly way
  src/components/checkbox/checkbox.js
  src/components/checkbox/checkbox.scss
  src/components/checkbox/checkbox.spec.js
  src/components/checkbox/demoLabels/index.html
  src/components/checkbox/demoLabels/script.js
  src/components/checkbox/demoLabels/style.css
Labels: - Breaking Change, P3: important, a11y, cla: yes, g3: reported, pr: lgtm, pr: merge ready

#10491 fix(md-chips): change md-icon class to inherit size
  src/components/chips/chips.scss
Labels: P1: urgent, cla: yes, pr: lgtm, pr: merge ready, severity: regression, type: bug

#11438 fix(tabs): update min-width to follow the spec
  src/components/tabs/tabs.scss
Labels: - Breaking Change, P3: important, cla: yes, pr: merge ready, severity: regression, type: bug, type: spec alignment
