Repository angular/material, pull requests merged in 2020-03, with the labels that each got.

#11792 refactor(radio-button): improve JSDoc
  src/components/radioButton/radio-button.js
Labels: P5: nice to have, cla: yes, pr: merge ready, type: chore

#11578 fix(autocomplete): scroll to top of the list each time dropdown open
  src/components/autocomplete/autocomplete.spec.js
  src/components/autocomplete/js/autocompleteController.js
Labels: P5: nice to have, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11798 fix(nav-bar): clicked nav item not focused or selected in some cases
  src/components/navBar/navBar.js
Labels: P1: urgent, cla: yes, pr: merge ready, severity: regression, type: bug

#11777 fix(autocomplete): clicking options pop-up scrollbar on IE closes pop-up
  src/components/autocomplete/js/autocompleteDirective.js
Labels: P2: required, browser: IE, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11845 fix(gesture): 'drag' gestures don't clean up touch action styles on parent
  src/components/bottomSheet/bottom-sheet.js
  src/core/services/gesture/gesture.js
  src/core/services/gesture/gesture.spec.js
  src/core/util/util.js
Labels: P2: required, cla: yes, g3: sync, pr: merge ready, type: bug, type: gestures, ui: mobile

#11802 fix(list): isEventFromControl() works on all browsers now
  src/components/list/demoListControls/script.js
  src/components/list/demoListControls/style.css
  src/components/list/list.js
  src/core/util/util.js
Labels: P2: required, browser: FireFox, browser: IE, browser: MS Edge, browser: Safari, cla: yes, pr: merge ready, type: bug

#11803 fix(list): secondary actions give aria warning if text is in a span
  src/components/list/list.js
  src/components/list/list.spec.js
Labels: P2: required, a11y, cla: yes, pr: merge ready, type: bug

#11156 fix(select): when using trackBy, trigger ng-change only when tracked property is different
  src/components/select/demoTrackBy/index.html
  src/components/select/demoTrackBy/script.js
  src/components/select/demoTrackBy/style.css
  src/components/select/select.js
  src/components/select/select.spec.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11868 chore: fix lint issue caused by PR #11156
  src/components/select/select.spec.js
Labels: P2: required, cla: yes, pr: merge ready, type: chore

#11818 fix(datepicker): reset inputFocusedOnWindowBlur flag
  src/components/datepicker/js/datepickerDirective.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready

#11846 fix(menu-bar): z-index not restored on menu close
  src/components/menu/js/menuController.js
  src/components/menu/js/menuDirective.js
  src/components/menuBar/js/menuBarController.js
  src/components/menuBar/menu-bar.spec.js
Labels: P3: important, cla: yes, g3: sync, pr: lgtm, pr: merge ready, type: bug, ui: CSS

#11855 fix(select): sanitize user input before searching options
  src/components/autocomplete/js/highlightController.js
  src/components/select/select.js
  src/core/util/util.js
  src/core/util/util.spec.js
Labels: P3: important, cla: yes, for: external contributor, pr: merge ready, type: bug

#11853 build: add @types/angular
  package-lock.json
  package.json
Labels: P4: minor, cla: yes, pr: merge ready, type: build

#11817 fix(autocomplete): loop options list when moving past first/last option with arrow keys
  src/components/autocomplete/autocomplete.spec.js
  src/components/autocomplete/js/autocompleteController.js
Labels: P2: required, a11y, cla: yes, g3: reported, g3: sync, pr: lgtm, pr: merge ready, type: bug

#11871 fix(contact-chips): don't rely on debug info to get access to controller scope
  src/components/chips/contact-chips.spec.js
  src/components/chips/js/contactChipsController.js
Labels: P2: required, browser: IE, cla: yes, pr: lgtm, pr: merge ready, severity: regression, type: bug

#11761 fix(select): overhaul screen reader support
  docs/app/css/style.css
  src/components/select/demoBasicUsage/index.html
  src/components/select/demoOptionGroups/index.html
  src/components/select/select-theme.scss
  src/components/select/select.js
  src/components/select/select.spec.js
  src/core/util/util.js
Labels: P2: required, a11y, cla: yes, g3: reported, g3: sync, pr: merge ready, pr: presubmit-failures, type: bug

#11874 chore(release): support publishing to NPM with tags other than latest
  release.js
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: chore

#11877 fix(list): primary action is fired twice on space/enter keydown
  src/components/list/list.js
Labels: P1: urgent, a11y, cla: yes, hotlist: Angular 1.6 support, pr: merge ready, severity: regression, type: bug

#11876 chore(deps): update dgeni-packages, octokit/rest, ajv, jshint
  package-lock.json
  package.json
Labels: P2: required, cla: yes, pr: merge ready, type: build

#11875 fix(autocomplete): md-not-found template is not styled properly
  docs/app/css/style.css
  src/components/autocomplete/js/autocompleteDirective.js
Labels: P1: urgent, cla: yes, pr: merge ready, severity: regression, type: bug

#11881 docs: fix hljs examples breaking
  package-lock.json
  package.json
Labels: P1: urgent, cla: yes, pr: merge ready, type: docs

#11880 chore: clean up BUILD guide
  docs/README.md
  docs/guides/BUILD.md
  gulp/tasks/server.js
  gulp/tasks/watch-demo.js
  package.json
  scripts/circleci/run-tests.sh
  scripts/snapshot-docs-site.sh
Labels: P3: important, cla: yes, pr: merge ready, type: chore

#11879 chore: add VSCode configuration and guide
  .vscode/README.md
  .vscode/extensions.json
  .vscode/settings.json
Labels: P3: important, cla: yes, pr: merge ready, type: chore
