Repository angular/material, pull requests merged in 2020-12, with the labels that each got.

#12049 fix(theming): fix CSS with nested rules parsing when registering a theme
  src/core/services/theming/theming.js
  src/core/services/theming/theming.spec.js
Labels: P2: required, cla: no, pr: lgtm, pr: merge ready, type: bug, ui: CSS, ui: theme

#12050 feat(chips): md-max-chips support for md-contact-chips
  src/components/chips/js/chipsController.js
  src/components/chips/js/contactChipsDirective.js
Labels: P4: minor, pr: lgtm, pr: merge ready, type: enhancement

#12048 ci: update CircleCI to 2.1, NodeJS to 14.15.1
  .circleci/config.yml
  .nvmrc
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: build

#12053 ci: use CircleCI build-tools' merge-with-parent command
  .circleci/config.yml
Labels: P1: urgent, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: build

#12057 build: fix audit warnings related to ini
  package-lock.json
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: build

#12058 fix(menu): menu focus is lost when menu-item has custom content
  src/components/menu/js/menuServiceProvider.js
Labels: P3: important, a11y, cla: yes, pr: lgtm, pr: merge ready, ui: focus

#12059 feat(autocomplete): allow localization of query result announcements
  src/components/autocomplete/js/autocompleteController.js
  src/components/autocomplete/js/autocompleteDirective.js
Labels: P2: required, a11y, cla: yes, g3: reported, g3: sync, i18n: localization, pr: lgtm, pr: merge ready, type: enhancement

#12060 feat(datepicker): add input-aria-describedby and input-aria-labelledby
  src/components/datepicker/demoBasicUsage/index.html
  src/components/datepicker/demoValidations/index.html
  src/components/datepicker/js/datepickerDirective.js
Labels: P2: required, a11y, cla: yes, g3: reported, g3: sync, pr: lgtm, pr: merge ready, type: enhancement

#12063 fix(select): form remains valid after empty option is selected
  src/components/select/demoValidations/index.html
  src/components/select/select.js
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, type: bug

#12062 fix(select): floating label hidden w/ placeholder and no value
  src/components/select/select.js
  src/components/select/select.scss
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, type: bug, ux: integration

#12061 fix(dialog): shift+tab does not cycle through tabbable elements
  src/components/dialog/dialog.js
  src/core/util/util.js
Labels: P2: required, a11y, cla: yes, g3: sync, pr: lgtm, pr: merge ready

#12064 fix(autocomplete): prevent flashing of invalid state
  src/components/autocomplete/js/autocompleteController.js
Labels: P5: nice to have, cla: yes, needs: squash commits, pr: lgtm, pr: merge ready, type: bug, ux: polish

#12067 fix(fab-speed-dial): action items are in tab order when closed
  src/components/fabActions/fabActions.js
  src/components/fabActions/fabActions.spec.js
Labels: P3: important, a11y, cla: yes, pr: lgtm, pr: merge ready

#12065 fix(fab-speed-dial): opens when trigger button is disabled
  src/components/button/button.scss
  src/components/fabSpeedDial/demoBasicUsage/style.scss
  src/components/fabSpeedDial/fabController.js
  src/components/fabSpeedDial/fabSpeedDial-theme.scss
  src/components/fabSpeedDial/fabSpeedDial.js
  src/components/fabSpeedDial/fabSpeedDial.spec.js
  src/components/fabToolbar/fabToolbar.scss
  src/core/util/util.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready

#12066 fix(fab-speed-dial): keyboard navigation issues with tab and shift+tab
  src/components/button/demoBasicUsage/index.html
  src/components/fabSpeedDial/demoBasicUsage/index.html
  src/components/fabSpeedDial/fabController.js
  src/components/fabSpeedDial/fabSpeedDial-theme.scss
  src/components/fabSpeedDial/fabSpeedDial.js
  src/components/fabToolbar/fabToolbar.js
Labels: P3: important, a11y, cla: yes, pr: lgtm, pr: merge ready
