Repository angular/material, pull requests merged in 2020-07, with the labels that each got.

#11376 feat(theme): add contrast opacity values for all color types and hues
  docs/guides/THEMES_IMPL_NOTES.md
  src/components/colors/demoBasicUsage/index.html
  src/components/colors/demoBasicUsage/regularCard.tmpl.html
  src/components/colors/demoBasicUsage/script.js
  src/components/colors/demoBasicUsage/style.css
  src/components/colors/demoBasicUsage/userCard.tmpl.html
  src/components/colors/demoThemePicker/index.html
  src/components/colors/demoThemePicker/script.js
  src/components/colors/demoThemePicker/style.css
  src/core/services/theming/theming.js
  src/core/services/theming/theming.spec.js
Labels: P1: urgent, a11y, cla: no, g3: reported, pr: merge ready, type: enhancement, ui: theme

#11378 fix(toolbar): input placeholders and ink need more contrast
  src/components/input/input-theme.scss
  src/components/toolbar/demoInputsInToolbar/index.html
  src/components/toolbar/demoInputsInToolbar/script.js
  src/components/toolbar/demoInputsInToolbar/style.scss
  src/components/toolbar/toolbar-theme.scss
Labels: P1: urgent, a11y, cla: yes, g3: reported, pr: lgtm, pr: merge ready, type: bug, ui: theme

#11958 fix(panel): don't throw exceptions when the groupName is a string
  src/components/panel/panel.js
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11959 docs: fix numerous IE11 layout issues
  docs/app/css/style.css
  docs/config/template/index.template.html
  package.json
  src/components/autocomplete/demoBasicUsage/index.html
  src/components/autocomplete/demoCustomTemplate/index.html
  src/components/autocomplete/demoFloatingLabel/index.html
  src/components/autocomplete/demoInsideDialog/index.html
  src/components/autocomplete/demoRepeatMode/index.html
  src/components/checkbox/demoBasicUsage/index.html
  src/components/checkbox/demoBasicUsage/style.css
  src/components/checkbox/demoSelectAll/index.html
  src/components/checkbox/demoSelectAll/style.css
  src/components/checkbox/demoSyncing/index.html
  src/components/checkbox/demoSyncing/style.css
  src/components/content/demoBasicUsage/index.html
  src/components/content/demoBasicUsage/style.css
  src/components/menuBar/demoBasicUsage/index.html
  src/components/menuBar/demoBasicUsage/style.scss
  src/components/menuBar/demoDynamicNestedMenus/index.html
  src/components/menuBar/demoDynamicNestedMenus/style.scss
  src/components/progressCircular/demoBasicUsage/index.html
  src/components/select/demoTrackBy/index.html
  src/components/toast/demoCustomUsage/style.scss
  src/components/toast/demoCustomUsage/toast-template.html
  src/components/toolbar/demoBasicUsage/index.html
  src/components/toolbar/demoBasicUsage/style.scss
Labels: P2: required, browser: IE, cla: yes, pr: lgtm, pr: merge ready, type: docs

#11870 build: replace deprecated gulp-cssnano with gulp-postcss
  gulp/util.js
  package-lock.json
  package.json
  scripts/gulp-utils.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, type: build

#11956 chore: Fix privacy concerns
  .mailmap
Labels: P5: nice to have, cla: yes, pr: lgtm, pr: merge ready

#11965 fix(nav-bar): throws exception when indexing null tabs variable
  src/components/navBar/navBar.js
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11957 fix(checkbox): labels with links throw exception in IE11
  src/components/checkbox/checkbox.js
Labels: P2: required, a11y, browser: IE, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11964 fix(nav-bar): null check tabs when finding tab
  src/components/navBar/navBar.js
  src/components/navBar/navBar.spec.js
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11968 fix(panel): demos need to access locals in controller's $onInit
  src/components/bottomSheet/bottom-sheet.js
  src/components/dialog/dialog.js
  src/components/panel/demoBasicUsage/index.html
  src/components/panel/demoBasicUsage/script.js
  src/components/panel/demoPanelAnimations/script.js
  src/components/panel/demoPanelProvider/script.js
  src/components/panel/demoReuse/script.js
  src/components/panel/panel.js
  src/components/toast/toast.js
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, type: demos, type: docs

#11972 fix(button): horizontal padding should match the spec
  src/components/button/button.scss
  src/components/button/demoBasicUsage/index.html
  src/components/button/demoDense/index.html
  src/components/button/demoDense/script.js
  src/components/button/demoDense/style.css
  src/core/style/_variables.scss
Labels: - Breaking Change, CSS: High Density, P2: required, cla: yes, g3: reported, pr: merge ready, type: spec alignment, ui: CSS

#11970 fix(select): md-select-header closes on mouse click when not using multiple
  src/components/select/demoBasicUsage/style.css
  src/components/select/demoSelectHeader/index.html
  src/components/select/demoSelectHeader/script.js
  src/components/select/demoSelectHeader/style.css
  src/components/select/select.js
Labels: P1: urgent, cla: yes, pr: merge ready, severity: regression, type: bug

#11971 fix(list): fix checkbox alignment and match dense heights to spec
  src/components/button/button.scss
  src/components/list/list.scss
  src/core/style/_variables.scss
Labels: - Breaking Change, CSS: High Density, P1: urgent, cla: yes, pr: lgtm, pr: merge ready, severity: regression, type: bug, type: spec alignment, ui: CSS

#11976 chore: merge --strategy=theirs no longer exists
  release.js
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: chore

#11977 chore: remove duplicate 1.2.0-rc.1 entries
  CHANGELOG.md
Labels: P2: required, cla: yes, pr: merge ready, pr: merge safe, type: chore

#11979 refactor(interimElement): no longer pass controller to options.onShow()
  src/components/dialog/dialog.js
  src/components/toast/toast.js
  src/core/services/compiler/compiler.js
  src/core/services/interimElement/interimElement.js
Labels: P3: important, cla: yes, pr: merge ready, type: docs

#11981 feat(layouts): add @mixin for responsive support for rows
  src/components/checkbox/checkbox.js
  src/components/checkbox/checkbox.scss
  src/components/divider/divider-theme.scss
  src/components/divider/divider.scss
  src/components/input/input.js
  src/components/radioButton/radio-button.js
  src/components/radioButton/radio-button.scss
  src/components/select/demoBasicUsage/style.css
  src/components/select/select.js
  src/core/style/_mixins.scss
  src/core/style/_variables.scss
  src/core/style/structure.scss
Labels: - Breaking Change, CSS: High Density, P2: required, cla: no, pr: lgtm, pr: merge ready, ui: layout

#11985 build(modules): configure more components to depend on input variables
  gulp/util.js
Labels: P1: urgent, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: build

#11987 fix(radio-button): when no value selected, first button not announced on focus
  src/components/dialog/demoBasicUsage/script.js
  src/components/radioButton/demoBasicUsage/index.html
  src/components/radioButton/demoBasicUsage/script.js
  src/components/radioButton/demoBasicUsage/style.css
  src/components/radioButton/demoMultiColumn/index.html
  src/components/radioButton/demoMultiColumn/script.js
  src/components/radioButton/demoMultiColumn/style.css
  src/components/radioButton/radio-button.js
  src/core/util/iterator.js
Labels: P2: required, a11y, cla: yes, pr: lgtm, pr: merge ready, type: bug

#11986 build: update dev dependencies
  package-lock.json
  package.json
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, type: build

#11988 fix(autocomplete): change md-escape-options default to 'clear'
  src/components/autocomplete/autocomplete.spec.js
  src/components/autocomplete/demoBasicUsage/index.html
  src/components/autocomplete/js/autocompleteController.js
  src/components/autocomplete/js/autocompleteDirective.js
Labels: P3: important, a11y, cla: yes, pr: merge ready, type: bug

#11989 fix(chips): update to latest Material Design spec (2017) updates
  src/components/chips/chips-theme.scss
  src/components/chips/chips.scss
  src/components/chips/demoBasicUsage/index.html
  src/components/chips/demoBasicUsage/style.scss
  src/components/chips/js/chipRemoveDirective.js
  src/components/chips/js/chipsDirective.js
Labels: P3: important, cla: yes, pr: lgtm, type: bug, type: spec alignment, ui: CSS

#11991 fix(chips): placeholder is truncated even though there is room
  src/components/chips/chips.scss
  src/components/chips/demoBasicUsage/index.html
  src/components/chips/demoBasicUsage/style.scss
  src/components/chips/js/chipsController.js
  src/components/chips/js/chipsDirective.js
  src/components/chips/js/contactChipsController.js
  src/components/chips/js/contactChipsDirective.js
Labels: P2: required, cla: yes, g3: sync, pr: lgtm, severity: regression, type: bug
