Repository angular/material, pull requests merged in 2020-09, with the labels that each got.

#12006 fix(calendar, datepicker): fix MomentJS custom format support
  config/karma-docs.conf.js
  config/karma.conf.js
  src/components/datepicker/js/dateLocale.spec.js
  src/components/datepicker/js/dateUtil.js
  src/components/datepicker/js/datepickerDirective.spec.js
Labels: P1: urgent, cla: yes, pr: merge ready, type: bug

#12007 fix(calendar, datepicker): fix MomentJS custom format support
  config/karma-docs.conf.js
  config/karma.conf.js
  package-lock.json
  src/components/datepicker/js/dateLocale.spec.js
  src/components/datepicker/js/dateUtil.js
  src/components/datepicker/js/datepickerDirective.spec.js
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready, type: bug

#12009 docs($mdSticky): update and clarify the usage and behavior
  src/components/sticky/sticky.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#12013 fix(radio-button): Cannot read property 'nodeName' of null
  src/components/radioButton/radio-button.js
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, severity: regression, type: bug

#12011 docs(a11y): add a list of supported screen readers
  .github/ISSUE_TEMPLATE.md
  README.md
  docs/app/partials/home.tmpl.html
Labels: P1: urgent, a11y, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#12012 fix(dialog): remove focus trap focus listeners onRemove
  package-lock.json
  src/components/dialog/demoBasicUsage/script.js
  src/components/dialog/dialog.js
  src/core/util/animation/animate.js
Labels: P1: urgent, cla: yes, pr: merge ready, severity: memory leak, severity: performance, type: performance

#12014 fix(radio-button): support selection using the space key
  src/components/radioButton/radio-button.js
Labels: P2: required, a11y, cla: yes, g3: reported, g3: sync, pr: merge ready, type: bug

#12015 fix(select): in popup, hover and focus background colors are the same
  src/components/select/select-theme.scss
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, ui: CSS, ui: focus, ux: polish

#12016 fix(typography): enable iOS long-press context menus
  src/core/style/typography.scss
Labels: P3: important, cla: yes, os: iOS, pr: lgtm, pr: merge ready, type: bug, type: ionic, ui: CSS, ux: integration

#12019 fix(icon): providing empty alt or aria-label attributes do not hide them from a11y
  src/components/icon/demoFontIconsWithClassnames/index.html
  src/components/icon/demoFontIconsWithClassnames/script.js
  src/components/icon/js/iconDirective.js
  src/core/services/aria/aria.js
Labels: P2: required, a11y, cla: yes, g3: reported, g3: sync, pr: lgtm, pr: merge ready, type: bug, type: docs

#12018 docs(home): simplify and clarify policy is for major versions
  docs/app/partials/home.tmpl.html
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#12020 test: update test name to removal usage of blacklist
  src/core/services/aria/aria.spec.js
Labels: P3: important, cla: yes, g3: pr, pr: lgtm, pr: merge ready, pr: merge safe, type: chore

#12021 docs(icon): documentation refinement and cleanup
  src/components/icon/js/iconService.js
Labels: P4: minor, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, type: docs

#12022 fix(list): case where list items are read twice by screen readers
  src/components/list/list.js
  src/components/list/list.spec.js
  src/core/services/aria/aria.js
Labels: P2: required, a11y, cla: yes, g3: reported, g3: sync, pr: lgtm, pr: merge ready, type: bug

#12023 fix(calendar): allow tabbing out when in standalone mode
  src/components/datepicker/js/calendar.js
Labels: P2: required, a11y, cla: yes, pr: lgtm, pr: merge ready, type: bug
