Repository angular/material, pull requests merged in 2021-11, with the labels that each got.

#12130 chore(npm): update dependencies and fix audit issues
  package-lock.json
  package.json
Labels: type: chore, pr: merge ready, P2: required, cla: yes, dependencies

#12132 docs(api): fix API docs rendering
  package-lock.json
  package.json
Labels: type: docs, pr: merge ready, P1: urgent, cla: yes

#12131 chore(sass): migrate from node-sass to sass
  .circleci/config.yml
  docs/gulpfile.js
  gulp/tasks/build-module-demo.js
  gulp/tasks/build-scss.js
  gulp/util.js
  package-lock.json
  package.json
Labels: type: chore, pr: merge ready, P1: urgent, cla: yes, os: macOS, dependencies

#12112 build: fix SCSS division deprecation
  gulp/config.js
  src/components/bottomSheet/bottom-sheet.scss
  src/components/button/button.scss
  src/components/card/card.scss
  src/components/chips/chips.scss
  src/components/datepicker/datePicker.scss
  src/components/fabSpeedDial/fabSpeedDial.scss
  src/components/fabToolbar/fabToolbar.scss
  src/components/input/_input-variables.scss
  src/components/input/input.scss
  src/components/list/list.scss
  src/components/menu/menu.scss
  src/components/progressLinear/progress-linear.scss
  src/components/select/select.scss
  src/components/slider/slider.scss
  src/components/switch/switch.scss
  src/core/services/layout/layout-attributes.scss
  src/core/style/_mixins.scss
  src/core/style/_variables.scss
  src/core/style/layout.scss
Labels: ui: CSS, pr: merge ready, P2: required, cla: yes
