Repository angular/material, pull requests merged in 2021-06, with the labels that each got.

#12103 build: update deps to fix security advisories and update to Karma v6
  gulp/tasks/karma-fast.js
  gulp/tasks/karma-sauce.js
  gulp/tasks/karma-watch.js
  gulp/tasks/karma.js
  package-lock.json
  package.json
Labels: P2: required, cla: yes, dependencies, pr: merge ready

#12080 feat(menu): render backdrop to parent
  src/components/menu/js/menuServiceProvider.js
  src/components/menu/menu.spec.js
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready

#12111 build: update hosted-git-info to fix security advisories
  package-lock.json
  package.json
Labels: P2: required, cla: yes, dependencies, pr: lgtm, pr: merge ready, type: build
