Repository angular/material, pull requests merged in 2021-12, with the labels that each got.

#12137 docs(eol): Add EOL options text and link to LTS section of landing page
  docs/app/partials/home.tmpl.html
Labels: cla: yes

#12138 chore(sass): fix module builds
  .circleci/config.yml
  gulp/config.js
  gulp/util.js
  package-lock.json
  scripts/gulp-utils.js
  src/core/style/_modules.scss
  src/core/style/_variables.scss
Labels: type: build, type: chore, pr: merge ready, P1: urgent, pr: lgtm

#12139 docs(eol): add EOL options banner to header of every page
  docs/app/css/style.css
  docs/config/template/index.template.html
Labels: pr: merge ready, P2: required, pr: lgtm
